
spring.application.name=sportcenter

#database
spring.data.mongodb.uri=${DATABASE_URI}
spring.data.mongodb.database=${DATABASE_VERSION}

#jwt
jwt.secret-key=${JWT_SECRET_KEY}

#mail
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_EMAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

client.url=${CLIENT_URL}
default.icon=${DEFAULT_ICON}



