
spring.application.name=sportcenter

#database
spring.data.mongodb.uri=${DATABASE_URI}
spring.data.mongodb.database=${DATABASE_VERSION}

#jwt
jwt.secret-key=${JWT_SECRET_KEY}

#mail
admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_EMAIL_PASSWORD}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

client.url=${CLIENT_URL}
default.icon=${DEFAULT_ICON}

cloud_name=${CLOUD_NAME}
cloud_api_key=${CLOUD_API_KEY}
cloud_api_secret=${CLOUD_API_SECRET}

#kich thuoc toi da cloudinary
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

#vnpay
vnpay.pay-url=${VNPAY_PAY_URL}
vnpay.return-url=${VNPAY_RETURN_URL}
vnpay.tmn-code=${VNPAY_TMN_CODE}
vnpay.secret-key=${VNPAY_SECRET_KEY}
vnpay.api-url=${VNPAY_API_URL}
vnpay.version=${VNPAY_VERSION}
vnpay.command=${VNPAY_COMMAND}
vnpay.order-type=${VNPAY_ORDER_TYPE}
vnpay.return-client-success=${VNPAY_RETURN_CLIENT_URL_SUCCESS}
vnpay.return-client-failed=${VNPAY_RETURN_CLIENT_URL_FAILED}
